  server:
    port: 8092
  spring:
    application:
      name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
