server:
  port: 8092

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}  # Docker Compose'dan gelen Kafka sunucu adresi

    consumer:
      group-id: notification-group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
